### ISSUE TITLE
can't open it after close

### ISSUE THREAD

**Issue by taojunnan** [kevinwarne/vue-balloon#3]
In example demo, I closed the single balloon, then click the Single Balloon Button can't open it again.

**Comment by taojunnan** [comment]
by the way, can I Custom minimize or maximize size

**Comment by kevinwarne** [comment]
This is desired functionality. When the balloon is "closed" it has a "close" flag that is set. In order to reopen the balloon you would need to programmatically call the `open` method on the balloon (preferred) or rerender the balloon component (which is what happens when you switch routes from multiple back to single). So we could implement this functionality by assigning a ref to the balloon component `ref = 'balloon'` and then re-opening the balloon on the Single Balloon button click `@click = '$refs.balloon.open'`. 

As far as customizing the sizes. All of the sizing is done with css so this can be configured with custom styles. However as it is now you will probably need to use `!important` css flags to override built in styles. In the future I'll work on adding an option to disable default styling in case you want to provide your own.

You can see the default styles that are used here https://github.com/kevinwarne/vue-balloon/blob/master/src/styles/balloon.scss

Hope this helps! 😃

**Comment by taojunnan** [comment]
Thank you for your reply. It works.
Now, I have more components(different template), I want to fixed on the same page one by one. However, the example of 'Multiple Balloons‘  in github it seems  to  use one  template .. if I want to create more different template for every balloon. What should I do? thanks

**Comment by kevinwarne** [comment]
Glad to hear it worked.

That use case is a bit tricky. Scoped slots make it difficult to use per balloon custom templates. But I see two ways of doing it using the multiple balloon. First in the template you could just use type on the balloon object and then conditionally render the proper component.

```html
<template>
  <div id = 'demo'>
    <balloon-set
      position = 'bottom-right'
      :balloons = 'balloons'
    >
      <template scope = 'balloon'>
        <component-a v-if = 'balloon.type === "a"'>
        </component>

        <component-b v-if = 'balloon.type === "b"'>
        </component>
      </template>
    </balloon-set>
  </div>
</template>

<script>
  import { BalloonSet } from 'vue-balloon'
  import ComponentA from './path/to/component-a'
  import ComponentB from './path/to/component-b'

  export default {
    components: {
      BalloonSet,
      ComponentA,
      ComponentB
    },

    data () {
      return {
        balloons: [
          {
            key: 1,
            title: 'Balloon A',
            type: 'a'
          },
          {
            key: 2,
            title: 'Balloon B',
            type: 'b'
          }
        ]
      }
    }
  }
</script>
```

Note: In this example we could have used an html template rather than nested components if that is preferred.

Or if your different components to be rendered in your balloon use a similar interface you could us a [dynamic component](https://vuejs.org/v2/guide/components.html#Dynamic-Components):

```html
<template>
  <div id = 'demo'>
    <balloon-set
      position = 'bottom-right'
      :balloons = 'balloons'
    >
      <template scope = 'balloon'>
        <component :is = 'balloon.type'>
        </component>
      </template>
    </balloon-set>
  </div>
</template>

<script>
  import { BalloonSet } from 'vue-balloon'
  import ComponentA from './path/to/component-a'
  import ComponentB from './path/to/component-b'

  export default {
    components: {
      BalloonSet,
      ComponentA,
      ComponentB
    },

    data () {
      return {
        balloons: [
          {
            key: 1,
            title: 'Balloon A',
            type: 'component-a'
          },
          {
            key: 2,
            title: 'Balloon B',
            type: 'component-b'
          }
        ]
      }
    }
  }
</script>
```

Hope this helps. Cheers!
